name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      # Cache Rust dependencies
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          
      # Cache cargo binaries
      - name: Cache cargo binaries
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      # The '|| true' ensures the command succeeds even if the binary is already installed from cache
      # Without this, the workflow would fail when trying to install an already existing binary
      - name: Install Dioxus CLI
        run: cargo install dioxus-cli --locked || true

      # Same here - '|| true' prevents failure if wasm-bindgen-cli is already in the cache
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.97 --locked || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install npm dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./tailwind.css -o ./assets/tailwind.css
        
      - name: Build Dioxus App
        run: dx build --release

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/dx/radar-graph/release/web/public'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4